### ISSUE TITLE
Request for Maintainers

### ISSUE THREAD

**Issue by sdiehl** [protolude/docs#1]
Setting up a issue for anyone who is interested in having a hand in and shaping [`protolude`](https://github.com/sdiehl/protolude) development. Too many libraries depend on this now for Stephen alone to decide what the API should be and as such I'm taking (a few) volunteers for anyone who wants to have commit access.

This library will be undergoing a large refactor for 0.3 with a few breaking changes and compatability for the unreleased GHC 8.10 which will diverge from `protolude-0.2.x` . This is a chance to fix a few small things about this library and create a new stable interface for the next few years.

Read the [design docs](https://github.com/protolude/docs/blob/master/DESIGN.md) and if you're interested let me know in the comments below.

**Comment by seagreen** [comment]
I'm in! I think a conservative alternate prelude that just grabs clear wins like removing partial functions is  really valuable, especially for beginners.

**Comment by rainbyte** [comment]
Not sure if I can help, but I have recently started to use protolude and really like it.
For me it would be cool to contribute and test simple things to learn more.

**Comment by sdiehl** [comment]
@rainbyte Certainly, I added a pretty vast test suite to test the whole cartesian product of [os, cabal ver, stack resolver, ghc] to make sure the library stays stable. Would certainly accept any patches to make it more robust.

See: https://github.com/protolude/protolude/actions
